[build]
  publish = "dist/"

  # Default build command.
  command = "yarn build"

[[redirects]]
  from = "/mete/*"
  to = "https://obscure-sea-30679.herokuapp.com/mete/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
